apiVersion: v2
name: neko
description: blah
type: application
version: 1.0.0
appVersion: v0.1.0
kubeVersion: ">=1.20.0-0"
keywords:
  - neko
  - monitoring
home: https://neko.guarandoo.moe
sources:
  - https://gitea.calliope.rip/guarandoo/neko
maintainers:
  - name: jmg.caguicla
    email: jmg.caguicla@guarandoo.me
icon: https://guarandoo.moe
annotations: