project_name: neko
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: neko
    dir: .
    main: ./cmd/server
nfpms:
  - id: default
    package_name: neko
    maintainer: John Mark Gabriel Caguicla <jmg.caguicla@guarandoo.me>
    description: An(other) uptime monitor
    homepage: https://git.calliope.rip/calliope/neko
    formats:
      - deb
      - rpm
      - archlinux
      - apk
    contents:
      - src: config.example.yaml
        dst: /etc/neko/config.yaml
        type: config|noreplace
      - src: package/systemd/neko.service
        dst: /usr/lib/systemd/system/neko.service
        packager: deb
      - src: package/systemd/neko.service
        dst: /usr/lib/systemd/system/neko.service
        packager: rpm
      - src: package/systemd/neko.service
        dst: /usr/lib/systemd/system/neko.service
        packager: archlinux
      - src: package/openrc/neko
        dst: /etc/init.d/neko
        packager: apk
gitea_urls:
  api: https://gitea.calliope.rip/api/v1
  download: https://gitea.calliope.rip
