project_name: neko
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: neko
    dir: .
    main: ./cmd/server
nfpms:
  - id: default
    package_name: neko
    formats:
      - deb
      - rpm
      - archlinux
gitea_urls:
  api: https://gitea.calliope.rip/api/v1
  download: https://gitea.calliope.rip