project_name: neko
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: neko
    dir: .
    main: ./cmd/server
nfpms:
  - id: default
    package_name: neko
    formats:
      - deb
      - rpm
      - archlinux
      - apk
    contents:
      - src: config.example.yaml
        dst: /etc/neko/config.yaml
      - src: alpine/neko
        dst: /etc/init.d/neko
gitea_urls:
  api: https://gitea.calliope.rip/api/v1
  download: https://gitea.calliope.rip
