instance: my-neko-instance-1
metrics:
  listenAddress: 127.0.0.1:3000
notifiers:
  my_discord_notifier:
    type: discord_webhook
    config:
      url: https://discord.com/api/webhooks/webhook_id/webhook_token
      # reuseMessage:
      #   enable: true
      #   lastMessageId:
      # messageTemplate: "{{.Name}}: {{.Status}}" # An optional message template, default: <MONITOR_NAME>: <STATUS>
  my_gotify_notifier:
    type: gotify
    config:
      url: https://gotify.example.com
      token: my-gotify-token
      # titleTemplate: "Monitor {{.Name}} is now {{.Status}}" # An optional title template, default: Monitor Status Change
      # messageTemplate: "{{.Name}}: {{.Status}}"             # An optional message template, default: <MONITOR_NAME>: <STATUS>
  my_smtp_notifier:
    type: smtp
    config:
      host: smtp.example.com
      port: 587
      username: smtp_user
      password: smtp_secret
      sender: neko@example.com
      recipients:
        - john.doe@example.com
      # subjectTemplate: "Monitor {{.Name}} is now {{.Status}}" # An optional title template, default: Monitor Status Change
      # bodyTemplate: "{{.Name}}: {{.Status}}"             # An optional message template, default: <MONITOR_NAME>: <STATUS>
monitors:
  - name: ssh-monitor
    interval: 1m
    probe:
      type: ssh
      config:
        host: some-machine.example.com
    notifiers:
      - my_discord_notifier
      - my_smtp_notifier
  - name: ping-monitor
    interval: 1m
    probe:
      type: ping
      config:
        address: some-machine.example.com
    notifiers:
      - my_discord_notifier
      - my_smtp_notifier
  - name: http-monitor
    interval: 1m
    probe:
      type: http
      config:
        address: https://example.com
        maxRedirects: 1
    notifiers:
      - my_discord_notifier
      - my_smtp_notifier
  - name: domain-monitor
    interval: 1d
    probe:
      type: domain
      config:
        domain: https://example.com
    notifiers:
      - my_discord_notifier
      - my_smtp_notifier
  - name: inverted-ping-monitor
    interval: 1m
    invert: true
    probe:
      type: ping
      config:
        address: host-that-is-normally-unreachable.example.com
    notifiers:
      - my_discord_notifier
      - my_smtp_notifier