instance: my-neko-instance-1
metrics:
  enable: false
  listenAddress: 127.0.0.1:3000
  extraLabels:
    region: usa-1a
# cluster:
#   enable: true
#   memberlist:
#     bindAddress: 0.0.0.0
#     bindPort: 7946
#     join: []
notifiers:
  my_discord_notifier:
    type: discord_webhook
    config:
      url: https://discord.com/api/webhooks/webhook_id/webhook_token
      # reuseMessage:
      #   enable: true
      #   lastMessageId:
      # messageTemplate: "{{.Name}}: {{.Status}}" # An optional message template, default: <MONITOR_NAME>: <STATUS>
  my_gotify_notifier:
    type: gotify
    config:
      url: https://gotify.example.com
      token: my-gotify-token
      # titleTemplate: "Monitor {{.Name}} is now {{.Status}}" # An optional title template, default: Monitor Status Change
      # messageTemplate: "{{.Name}}: {{.Status}}"             # An optional message template, default: <MONITOR_NAME>: <STATUS>
  my_smtp_notifier:
    type: smtp
    config:
      host: smtp.example.com
      port: 587
      username: smtp_user
      password: smtp_secret
      sender: neko@example.com
      recipients:
        - john.doe@example.com
      # subjectTemplate: "Monitor {{.Name}} is now {{.Status}}" # An optional title template, default: Monitor Status Change
      # bodyTemplate: "{{.Name}}: {{.Status}}"             # An optional message template, default: <MONITOR_NAME>: <STATUS>
monitors:
  - name: ssh-monitor
    interval: 1m
    # retry:
    #   maxAttempts: 5
    #   interval: 15s
    probe:
      type: ssh
      config:
        host: some-machine.example.com
        auth:
          user: root
          type: password
          config:
            password: super-secret-password
    notifiers:
      - name: my_discord_notifier
      - name: my_smtp_notifier
  - name: ping-monitor
    interval: 1m
    probe:
      type: ping
      config:
        address: some-machine.example.com
    notifiers:
      - name: my_discord_notifier
      - name: my_smtp_notifier
  - name: http-monitor
    interval: 1m
    probe:
      type: http
      config:
        address: https://example.com
        maxRedirects: 1
    notifiers:
      - name: my_discord_notifier
      - name: my_smtp_notifier
  - name: domain-monitor
    interval: 24h
    probe:
      type: domain
      config:
        domain: https://example.com
    notifiers:
      - name: my_discord_notifier
      - name: my_smtp_notifier
  - name: inverted-ping-monitor
    interval: 1m
    invert: true
    probe:
      type: ping
      config:
        address: host-that-is-normally-unreachable.example.com
    notifiers:
      - name: my_discord_notifier
      - name: my_smtp_notifier
