name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."gitea.calliope.rip"]
              http = true
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: gitea.calliope.rip
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GITEA_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "gitea.calliope.rip/guarandoo/neko:${{gitea.sha}},gitea.calliope.rip/guarandoo/neko:latest"