name: binary
on:
  push:
    tags:
      - "v*"
env:
  GITEA_REGISTRY: gitea.calliope.rip
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          force-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~> v2
          args: release -f .goreleaser.yaml --clean
        env:
          GITEA_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}